export const FACTION_NAMES_TO_CODES = {
  "Adepta Sororitas": "sisters",
  "Black Templars": "blackTemplars",
  "Blood Angels": "bloodAngels",
  "Dark Angels": "darkAngels",
  "Deathwatch": "deathwatch",
  "Imperial Fists": "imperialFists",
  "Iron Hands": "ironHands",
  "Raven Guard": "ravenGuard",
  "Salamanders": "salamanders",
  "Space Marines": "spaceMarines",
  "Space Wolves": "spaceWolves",
  "Ultramarines": "ultramarines",
  "White Scars": "whiteScars",
  "Adeptus Custodes": "custodes",
  "Adeptus Mechanicus": "mechanicus",
  "Aeldari": "aeldari",
  "Astra Militarum": "astra",
  "Chaos Daemons": "daemons",
  "Chaos Knights": "chaosKnights",
  "Drukhari": "drukhari",
  "Genestealer Cults": "gsc",
  "Grey Knights": "greyKnights",
  "Chaos Space Marines": "chaosMarines",
  "Death Guard": "deathGuard",
  "Emperor's Children": "emperorsChildren",
  "Thousand Sons": "thousandSons",
  "World Eaters": "worldEaters",
  "Imperial Agents": "imperialAgents",
  "Imperial Knights": "imperialKnights",
  "Leagues of Votann": "votann",
  "Necrons": "necrons",
  "Orks": "orks",
  "Tyranids": "tyranids",
  "T'au Empire": "tau",
};

export const FACTION_NAMES = {
  "sisters": "Adepta Sororitas",
  "blackTemplars": "Black Templars",
  "bloodAngels": "Blood Angels",
  "darkAngels": "Dark Angels",
  "deathwatch": "Deathwatch",
  "imperialFists": "Imperial Fists",
  "ironHands": "Iron Hands",
  "ravenGuard": "Raven Guard",
  "salamanders": "Salamanders",
  "spaceMarines": "Space Marines",
  "spaceWolves": "Space Wolves",
  "ultramarines": "Ultramarines",
  "whiteScars": "White Scars",
  "custodes": "Adeptus Custodes",
  "mechanicus": "Adeptus Mechanicus",
  "aeldari": "Aeldari",
  "astra": "Astra Militarum",
  "daemons": "Chaos Daemons",
  "chaosKnights": "Chaos Knights",
  "drukhari": "Drukhari",
  "gsc": "Genestealer Cults",
  "greyKnights": "Grey Knights",
  "chaosMarines": "Chaos Space Marines",
  "deathGuard": "Death Guard",
  "emperorsChildren": "Emperor's Children",
  "thousandSons": "Thousand Sons",
  "worldEaters": "World Eaters",
  "imperialAgents": "Imperial Agents",
  "imperialKnights": "Imperial Knights",
  "votann": "Leagues of Votann",
  "necrons": "Necrons",
  "orks": "Orks",
  "tyranids": "Tyranids",
  "tau": "T'au Empire",
};

export const FACTION_IMAGE_URLS = {
  "sisters": "/images/factions/sororitas.svg",
  "blackTemplars": "/images/factions/blackTemplars.svg",
  "bloodAngels": "/images/factions/bloodAngels.svg",
  "darkAngels": "/images/factions/darkAngels.svg",
  "deathwatch": "/images/factions/deathwatch.svg",
  "imperialFists": "/images/factions/imperialFists.svg",
  "ironHands": "/images/factions/ironHands.svg",
  "ravenGuard": "/images/factions/ravenGuard.svg",
  "salamanders": "/images/factions/salamanders.svg",
  "spaceMarines": "/images/factions/astartes.svg",
  "spaceWolves": "/images/factions/spaceWolves.svg",
  "ultramarines": "/images/factions/ultramarines.svg",
  "whiteScars": "/images/factions/whiteScars.svg",
  "custodes": "/images/factions/custodes.svg",
  "mechanicus": "/images/factions/mechanicus.svg",
  "astra": "/images/factions/militarum.svg",
  "greyKnights": "/images/factions/greyKnights.svg",
  "imperialAgents": "/images/factions/imperialAquila.svg",
  "imperialKnights": "/images/factions/imperialKnights.svg",

  "daemons": "/images/factions/chaosDaemons.svg",
  "chaosKnights": "/images/factions/questorTraitoris.svg",
  "chaosMarines": "/images/factions/hereticAstartes.svg",
  "deathGuard": "/images/factions/deathGuard.svg",
  "emperorsChildren": "/images/factions/emperorsChildren.svg",
  "thousandSons": "/images/factions/thousandSons.svg",
  "worldEaters": "/images/factions/worldEaters.svg",

  "aeldari": "/images/factions/asuryani.svg",
  "drukhari": "/images/factions/drukhari.svg",
  "gsc": "/images/factions/gsc.svg",
  "votann": "/images/factions/votann.svg",
  "necrons": "/images/factions/necrons.svg",
  "orks": "/images/factions/orks.svg",
  "tyranids": "/images/factions/tyranids.svg",
  "tau": "/images/factions/tau.svg",
};
  